import React, { useEffect } from 'react';
import Head from 'next/head';
import Navbar from '../navbar/Navbar';
import styles from './BasicLayout.module.css';
import Link from 'next/link';
import { useUserContext } from '@/contexts/UserContext';
import { useRouter } from 'next/router';
import { parseJwt } from 'lib/auth';

const BasicLayout = ({ children }) => {
  const { user } = useUserContext();
  const router = useRouter();

  useEffect(() => {
    if (router.pathname !== '/logs' && !user.accessToken) {
      router.push('/login');
      return;
    }
    const decoded = parseJwt(user.accessToken);
    if (decoded.exp < Date.now() / 1000) {
      router.push('/login');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user.accessToken]);

  return (
    <>
      <Head>
        <title>Jungle Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gorilla.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Navbar />
        {children}
        <div className="toast ">
          <div className="collapse rounded-lg p-0">
            <input type="checkbox" className="peer" />
            <div className="collapse-title bg-base-200  text-primary-dark text-center">
              for instructors/stakeholders
            </div>
            <div className="collapse-content bg-base-200 ">
              <div className={'flex gap-3 flex-col pt-1 p-0'}>
                <div className="card bg-primary rounded-md p-2 w-full ">
                  <Link
                    href={'/logs'}
                    className={'underline text-primary-dark'}
                  >
                    <p>Please Check the Release Log </p>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default BasicLayout;
