AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda local demo

Resources:
  LambdaDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda # format is projectPath/
      Handler: carts-lambda.Handler # format is filename.functionName
      Runtime: '>=14.0.0'
